version: "3"

services:
    node:
        image: kkarczmarczyk/node-yarn
        volumes:
            - ./:/app/
        working_dir: /app/
        networks:
            - public
        ports:
            - "9000:9000"
            - "9042:9042"
        environment:
            - NODE_ENV=development
        tty: true
        # command: yarn serve:dev

networks:
    public:
